version: '3.8'


services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=debug
      - POSTGRES_PASSWORD=debug
      - POSTGRES_DB=streamers_utils
      - POSTGRES_HOST_AUTH_METHOD=password
    ports:
      - 5432:5432

  service:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    depends_on:
      - db
    ports:
      - 8080:80
    working_dir: /app
    environment:
      PYTHONDONTWRITEBYTECODE: true
    volumes:
      - ../src/:/app/
